version: "3"
services:
  selenium-grid-hub:
    container_name: selenium-hub
    image: selenium/hub:3.141.59-vanadium
    ports:
      - 4444:4444

  selenium-grid-node-chrome:
    depends_on:
      - selenium-grid-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-chrome:3.141.59-vanadium
    volumes:
      - /dev/shm:/dev/shm

  selenium-grid-node-chrome-debug:
    depends_on:
      - selenium-grid-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-chrome-debug:3.141.59-vanadium
    ports:
      - 5901:5900
    volumes:
      - /dev/shm:/dev/shm

  test:
    container_name: test
    build: .
    command: "./node_modules/.bin/jest tests --maxWorkers=${MAX_WORKERS:-5}"
    depends_on:
      - selenium-grid-hub
    environment:
      - MAX_WORKERS=${MAX_WORKERS:-5}
      - SELENIUM_URL=http://selenium-grid-hub:4444/wd/hub
    volumes:
      - ./tests:/home/node/app/tests
      - ./utils:/home/node/app/utils

  test-debug:
    container_name: test-debug
    build: .
    command: "node --inspect ./node_modules/.bin/jest --runInBand=true tests"
    depends_on:
      - selenium-grid-node-chrome-debug
    environment:
      - SELENIUM_URL=http://selenium-grid-hub:4444/wd/hub
    volumes:
      - ./tests:/home/node/app/tests
      - ./utils:/home/node/app/utils
